### PR TITLE
Fake data generation and value list fixes

### LINKED ISSUE #217: WR fake data generation does not produce output for source files containing empty fields
I used White Rabbit v0.9.0 to generate fake data from a previous WR scan report. in this report, two of the source files contained empty fields (indicated as "empty" in the "Type" column of the scan report "Overview" sheet), see image below. As a result, the fake data generation produces an empty output for both files, ignoring ALL other fields which did contain data. No error is shown in the console. Fake data generation settings: Target data type set to "Delimited text files", tested with all CSV format options. Max rows per table seems irrelevant. Not tested by setting a target database. 

Screenshot 2020-03-26 at 12 13 47

**Suggested workaround** (until the issue is fixed): remove the empty fields from the "Overview" sheet in the WR ScanReport. Then the remaining fields are processed correctly and the output won't be empty.

### PR DESCRIPTION
**Pull request by MaximMoinat**
Implements three fixes:
* an off by one error causing the most occurring value to be slightly more prevalent and least occurring slightly less
* in RiaH field detail, if only top x values were scanned, show that the value list is truncated
* Fixes #217 

Two new features:
* add option for uniform sampling instead of using reported frequencies
* unique fields are also generated with unique values in the fake data (if enough scanned values available)

On refactoring:
* The value counts are  loaded in a dedicated class.

### CODE REVIEW

File: whiterabbit/src/main/java/org/ohdsi/whiteRabbit/fakeDataGenerator/FakeDataGenerator.java [hunk 1]
```diff
@@ -181,26 +182,23 @@ private boolean isInt(String type) {
...
-					int frequency = (int) (Double.parseDouble(valueCounts[i][1]));
-					totalFrequency += frequency;
-
-					values[i] = valueCounts[i][0];
-					cumulativeFrequency[i] = totalFrequency;
+					values[i] = valueCounts.get(i).getValue();
+					runningTotal += valueCounts.get(i).getFrequency();
+					cumulativeFrequency[i] = runningTotal;
 				}
+				totalFrequency = valueCounts.getSummedFrequency();
```
Comment (blootsvoets) [inline whiterabbit/src/main/java/org/ohdsi/whiteRabbit/fakeDataGenerator/FakeDataGenerator.java]: `= runningTotal`?

**Comment by MaximMoinat** [comment]
Tagging issues #201 and #217  as well
